version: '3'
services:
  streamlit-app:
    image: streamlit-demo 
    build: .
    #command: streamlit run src/test_st.py
    ports:
      - 8080:8080
    volumes:
      - ./src/:/opt/streamlit/src/