apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: HTTP
    requestPath: /healthcheck
  # securityPolicy:
  #   name: "armor-security-policy"
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-secret
  timeoutSec: 36000